// Copied app logic to web_weav scope, keeping Framer Tilt import here as requested
(function(){
  const $ = (sel, ctx = document) => ctx.querySelector(sel);
  const $$ = (sel, ctx = document) => Array.from(ctx.querySelectorAll(sel));
  const state = { user: null, events: [], publications: [], gallery: [], notifications: [] };
  function loadState(){ try{ Object.assign(state, JSON.parse(localStorage.getItem('ieee_sb_state')||'{}')); }catch(_){} }
  function saveState(){ localStorage.setItem('ieee_sb_state', JSON.stringify(state)); }
  function showToast(message, timeout=3000){ const t=$('#toast'); if(!t) return; t.textContent=message; t.classList.remove('hidden'); setTimeout(()=>t.classList.add('hidden'), timeout); }
  function smoothNav(){ $$('.nav-link').forEach(l=>l.addEventListener('click',()=>{ $$('.nav-link').forEach(x=>x.classList.remove('active')); l.classList.add('active'); })); }
  function setupMobileNav(){ const h=$('#hamburger'), n=$('.nav-links'); if(!h||!n) return; h.addEventListener('click',()=>{ const isOpen=getComputedStyle(n).display!=='none'; if(!isOpen){ Object.assign(n.style,{display:'flex',flexDirection:'column',position:'absolute',right:'20px',top:'70px',background:'#0d1626',padding:'12px',borderRadius:'12px',border:'1px solid rgba(255,255,255,0.12)',gap:'6px'});} else { n.removeAttribute('style'); }}); }
  function renderTeam(){ const team=[{name:'Dr. A. Advisor',role:'Faculty Advisor'},{name:'Jane Doe',role:'Chair'},{name:'John Smith',role:'Vice Chair'},{name:'Priya Kumar',role:'Secretary'},{name:'Wei Chen',role:'Treasurer'},{name:'Amir Ali',role:'Publicity Lead'}]; const grid=$('#teamGrid'); if(!grid) return; grid.innerHTML=team.map(m=>`<div class="card glass" style="text-align:center"><div style="width:96px;height:96px;border-radius:50%;margin:0 auto 10px;background:linear-gradient(135deg,#0e2239,#173251);"></div><h4 style="margin:6px 0 2px">${m.name}</h4><p style="margin:0;color:#b7c5d3">${m.role}</p></div>`).join(''); }
  function seedDemoData(){ if(!state.publications.length){ state.publications=[{title:'Deep Learning for Edge Devices',authors:'J. Doe, P. Kumar',link:'#',date:'2025-03-21'},{title:'6G Communication Paradigms',authors:'W. Chen',link:'#',date:'2025-05-02'},{title:'Robotics in Humanitarian Aid',authors:'A. Ali',link:'#',date:'2025-06-15'}]; } if(!state.events.length){ state.events=[{id:crypto.randomUUID(),title:'AI Hackathon',date:nextDate(7),venue:'Innovation Lab',desc:'48-hour build sprint',photos:[]},{id:crypto.randomUUID(),title:'5G Workshop',date:today(),venue:'Auditorium',desc:'Hands-on session',photos:[]},{id:crypto.randomUUID(),title:'Women in Tech Panel',date:prevDate(20),venue:'Seminar Hall',desc:'Leaders share insights',photos:[]}]; } }
  function today(){ return new Date().toISOString().slice(0,10); }
  function nextDate(d){ const x=new Date(); x.setDate(x.getDate()+d); return x.toISOString().slice(0,10); }
  function prevDate(d){ const x=new Date(); x.setDate(x.getDate()-d); return x.toISOString().slice(0,10); }
  function renderPublications(){ const track=$('#publicationsTrack'); if(!track) return; track.innerHTML=state.publications.map(p=>`<article class="card glass"><h4 style="margin:0 0 6px">${p.title}</h4><p style="margin:0;color:#b7c5d3">${p.authors}</p><div style="margin-top:10px;display:flex;justify-content:space-between;align-items:center"><span style="color:#b7c5d3">${p.date}</span><a href="${p.link}" class="btn btn-outline" target="_blank" rel="noopener">View</a></div></article>`).join(''); bindHScroll(track); }
  function statusForEvent(s){ const now=new Date(), d=new Date(s); if(d.toDateString()===now.toDateString()) return 'ongoing'; return d>now?'upcoming':'past'; }
  function renderEvents(filter='upcoming'){ const grid=$('#eventsGrid'); if(!grid) return; const items=state.events.filter(ev=>filter==='all'?true:statusForEvent(ev.date)===filter); grid.innerHTML=items.map(ev=>`<article class="card glass"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><h4 style="margin:0">${ev.title}</h4><span class="chip ${statusForEvent(ev.date)}">${statusForEvent(ev.date).toUpperCase()}</span></div><p style="margin:8px 0;color:#b7c5d3">${ev.desc||''}</p><div style="display:flex;gap:10px;color:#b7c5d3"><span>📅 ${ev.date}</span><span>📍 ${ev.venue}</span></div><div style="display:flex;gap:8px;margin-top:10px;flex-wrap:wrap">${ev.photos.slice(0,4).map(src=>`<img src="${src}" alt="${ev.title}" style="width:72px;height:72px;object-fit:cover;border-radius:10px;cursor:zoom-in" data-lightbox />`).join('')}</div></article>`).join(''); $$('[data-lightbox]', grid).forEach(img=>img.addEventListener('click',()=>openLightbox(img.src))); }
  function bindCalendarFilters(){ $$('.calendar-controls .chip').forEach(chip=>{ chip.addEventListener('click',()=>{ $$('.calendar-controls .chip').forEach(c=>c.classList.remove('active')); chip.classList.add('active'); renderEvents(chip.dataset.filter); }); }); }
  function renderDashboard(){ const dE=$('#dashEvents'); if(dE) dE.innerHTML=state.events.filter(e=>['upcoming','ongoing'].includes(statusForEvent(e.date))).slice(0,5).map(e=>`<div class="glass" style="padding:10px;border-radius:12px">${e.title} — ${e.date}</div>`).join(''); const dp=$('#dashPublications'); if(dp) dp.innerHTML=state.publications.slice(0,5).map(p=>`<div class="glass" style="padding:10px;border-radius:12px">${p.title}</div>`).join(''); const nl=$('#notificationsList'); if(nl) nl.innerHTML=(state.notifications||[]).slice(-5).reverse().map(n=>`<li class="glass" style="padding:10px;border-radius:12px">${n}</li>`).join(''); }
  function renderGallery(){ const grid=$('#galleryGrid'); const all=state.events.flatMap(e=>e.photos.map(src=>({src,title:e.title}))); if(grid){ grid.innerHTML=all.map(p=>`<img src="${p.src}" alt="${p.title}" data-lightbox />`).join(''); $$('[data-lightbox]', grid).forEach(img=>img.addEventListener('click',()=>openLightbox(img.src))); } const track=$('#carouselTrack'); if(track){ track.innerHTML=all.slice(0,10).map(p=>`<img src="${p.src}" alt="${p.title}" />`).join(''); bindCarousel(track); } }
  function openLightbox(src){ const lb=$('#lightbox'); if(!lb) return; $('#lightboxImg').src=src; lb.classList.remove('hidden'); }
  function closeLightbox(){ const lb=$('#lightbox'); if(lb) lb.classList.add('hidden'); }
  function bindLightbox(){ const c=$('#lightboxClose'); if(c) c.addEventListener('click', closeLightbox); const lb=$('#lightbox'); if(lb) lb.addEventListener('click',e=>{ if(e.target.id==='lightbox') closeLightbox(); }); }
  function bindCTA(){ const j=$('#ctaJoin'); j&&j.addEventListener('click',()=>location.hash='#about'); const l=$('#ctaLogin'); l&&l.addEventListener('click', openLoginModal); }
  function openLoginModal(){ const m=$('#loginModal'); if(!m) return; m.classList.remove('hidden'); m.setAttribute('aria-hidden','false'); }
  function closeLoginModal(){ const m=$('#loginModal'); if(!m) return; m.classList.add('hidden'); m.setAttribute('aria-hidden','true'); }
  function bindLoginModal(){ $('#openLogin')?.addEventListener('click', openLoginModal); $('#ctaLogin')?.addEventListener('click', openLoginModal); $('#closeLogin')?.addEventListener('click', closeLoginModal); $('#xCloseLogin')?.addEventListener('click', closeLoginModal); }
  function bindLoginForm(){ const f=$('#loginForm'); if(!f) return; f.addEventListener('submit',e=>{ e.preventDefault(); const name=$('#loginName').value.trim(); const email=$('#loginEmail').value.trim(); const membershipId=$('#loginId').value.trim(); if(!name||!email||!membershipId) return; const isAdmin=membershipId.toUpperCase().endsWith('-ADMIN'); state.user={name,email,membershipId,role:isAdmin?'admin':'member'}; state.notifications.push(`Welcome ${name}!`); saveState(); closeLoginModal(); updateAuthUI(); showToast(`Logged in as ${state.user.role}.`); }); }
  function updateAuthUI(){ const dash=$('#dashboard'); if(dash){ if(state.user){ dash.classList.remove('hidden'); $('#adminPanel')?.classList.toggle('hidden', state.user.role!=='admin'); } else { dash.classList.add('hidden'); } } renderDashboard(); }
  function bindEventForm(){ const form=$('#eventForm'); if(!form) return; form.addEventListener('submit',async e=>{ e.preventDefault(); const title=$('#eventTitle').value.trim(); const date=$('#eventDate').value; const venue=$('#eventVenue').value.trim(); const desc=$('#eventDesc').value.trim(); const files=$('#eventPhotos').files; const photos=await Promise.all(Array.from(files).map(toBase64)); const ev={id:crypto.randomUUID(),title,date,venue,desc,photos}; state.events.unshift(ev); if(photos.length) state.gallery.push(...photos); state.notifications.push(`New event: ${title} on ${date}`); saveState(); form.reset(); renderEvents($('.calendar-controls .chip.active')?.dataset.filter||'upcoming'); renderDashboard(); renderGallery(); showToast('Event added'); }); }
  function toBase64(file){ return new Promise((res,rej)=>{ const r=new FileReader(); r.onload=()=>res(r.result); r.onerror=rej; r.readAsDataURL(file); }); }
  function bindContactForm(){ const f=$('#contactForm'); f&&f.addEventListener('submit',e=>{ e.preventDefault(); $('#contactStatus').textContent='Thank you! We will get back to you soon.'; showToast('Message sent'); }); }
  function wireEventsSection(){ bindCalendarFilters(); renderEvents('upcoming'); }
  function wirePublicationsSection(){ renderPublications(); }
  function wireGallerySection(){ renderGallery(); }
  function initYear(){ const y=$('#year'); if(y) y.textContent=new Date().getFullYear(); }
  function init(){ loadState(); seedDemoData(); saveState(); initYear(); smoothNav(); setupMobileNav(); bindCTA(); bindLoginModal(); bindLoginForm(); bindEventForm(); bindContactForm(); bindLightbox(); renderTeam(); wireEventsSection(); wirePublicationsSection(); wireGallerySection(); updateAuthUI(); initAnimations(); bindAccordion(); bindDock(); }
  document.addEventListener('DOMContentLoaded', init);
  function initAnimations(){ const pre=document.getElementById('preloader'); if(pre) setTimeout(()=>pre.classList.add('hidden'),500); const el=document.querySelector('[data-typewriter]'); if(el){ const full=el.textContent; el.textContent=''; let i=0; const tick=()=>{ if(i<=full.length){ el.textContent=full.slice(0,i++); setTimeout(tick,24);} }; tick(); } const counters=[{sel:'#statMembers',target:120},{sel:'#statEvents',target:50},{sel:'#statPubs',target:20},{sel:'#statMembers2',target:198},{sel:'#statAlumni',target:146},{sel:'#statEvents2',target:34}]; const io=new IntersectionObserver((entries)=>{ entries.forEach(e=>{ if(e.isIntersecting){ const n=e.target; const text=n.textContent; const conf=counters.find(c=>c.sel.endsWith(n.id)||c.sel===`#${n.id}`); if(conf){ animateNumber(n, parseInt(String(conf.target),10), 800, text.includes('+')); } io.unobserve(n); } }); },{threshold:0.6}); counters.forEach(c=>{ const n=document.querySelector(c.sel); if(n) io.observe(n); }); document.querySelectorAll('.card.glass').forEach(card=>{ card.setAttribute('data-tilt',''); card.addEventListener('mousemove',(e)=>{ const r=card.getBoundingClientRect(); const px=(e.clientX-r.left)/r.width; const py=(e.clientY-r.top)/r.height; const rx=(py-0.5)*-8; const ry=(px-0.5)*8; card.style.transform=`rotateX(${rx}deg) rotateY(${ry}deg) translateY(-6px)`; }); card.addEventListener('mouseleave',()=>{ card.style.transform=''; }); }); initFramerTilt(); }
  function animateNumber(el,target,duration=800,plus=false){ const start=0; const t0=performance.now(); function frame(now){ const p=Math.min((now-t0)/duration,1); const eased=1-Math.pow(1-p,3); const val=Math.floor(start+(target-start)*eased); el.textContent=plus?`${val}+`:String(val); if(p<1) requestAnimationFrame(frame);} requestAnimationFrame(frame); }
  async function initFramerTilt(){ const url='https://framer.com/m/TiltCard-1-nBci.js@mSFBBLRp2Xy3wAzveJmu'; try{ const mod=await import(url); const cards=$$('.card.glass'); if(mod&&typeof mod.default==='function'){ mod.default(cards);} else if(mod&&typeof mod.attach==='function'){ mod.attach(cards);} else if(mod&&typeof mod.init==='function'){ mod.init(cards);} document.body.setAttribute('data-tilt','framer'); showToast && showToast('Framer Tilt enabled'); }catch(_){ document.body.setAttribute('data-tilt','fallback'); showToast && showToast('Using fallback tilt'); } }
  function bindHScroll(track){ const left=document.querySelector('[data-scroll-left]'); const right=document.querySelector('[data-scroll-right]'); if(!track||!left||!right) return; left.addEventListener('click',()=>track.scrollBy({left:-320,behavior:'smooth'})); right.addEventListener('click',()=>track.scrollBy({left:320,behavior:'smooth'})); }
  function bindCarousel(track){ const prev=document.getElementById('carouselPrev'); const next=document.getElementById('carouselNext'); let index=0; function update(){ const w=track.getBoundingClientRect().width; track.style.transform=`translateX(${-index*(w*0.66+12)}px)`; track.style.transition='transform .4s ease'; } prev?.addEventListener('click',()=>{ index=Math.max(0,index-1); update(); }); next?.addEventListener('click',()=>{ index=Math.min(track.children.length-1,index+1); update(); }); }
  function bindAccordion(){ $$('.accordion-item').forEach(item=>{ const btn=$('.accordion-header', item); btn.addEventListener('click',()=>{ item.classList.toggle('open'); }); }); }
  function bindDock(){ const items=$$('[data-dock]'); function onScroll(){ const sections=['home','events','publications','gallery','contact']; let current='home'; sections.forEach(id=>{ const el=document.getElementById(id); if(el){ const rect=el.getBoundingClientRect(); if(rect.top<window.innerHeight*0.35) current=id; } }); items.forEach(a=>a.classList.toggle('active', a.getAttribute('href')===`#${current}`)); } window.addEventListener('scroll', onScroll, {passive:true}); onScroll(); }
})();


